using System.ComponentModel.DataAnnotations;

namespace BabaFunkeNewsletterManager.Data.DTOs
{
    /// <summary>
    /// The SubscriberCreate DTO mirrors the Subscriber model and is used for creating Subscribers. 
    /// Among others, it excludes the Id property which is auto-generated by the Database
    /// </summary>
    public class SubscriberCreate
    {
        [Required]
        [MaxLength(20, ErrorMessage = "Cannot be longer than 50 characters")]
        public string Firstname { get; set; }
        [Required]
        [MaxLength(20, ErrorMessage = "Cannot be longer than 50 characters")]
        public string Lastname { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }

    }
}